In [1]:
!pip install numpy

In [2]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
#2D
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
#3d
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#initial place holders
#2D
np.zeros((1,2))

array([[0., 0.]])

In [6]:
np.zeros((1,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
#create an array of evenly spaced values(stepvalues)
a = np.arange(10,25,3)
print(a)

[10 13 16 19 22]


In [8]:
#array of evenly spaced values
uni = np.linspace(110,80,10)
print(uni)

[110.         106.66666667 103.33333333 100.          96.66666667
  93.33333333  90.          86.66666667  83.33333333  80.        ]


In [9]:
a = np.array([[[3,5,6],[4,6,7]],
              [[3,5,6],[4,6,7]],
              [[6,6,4],[4,8,9]]])
print(a)

[[[3 5 6]
  [4 6 7]]

 [[3 5 6]
  [4 6 7]]

 [[6 6 4]
  [4 8 9]]]


In [10]:
import numpy as np
a = np.array([[[1,5],[8,19]],[[35,52],[80,90]]])
print(a)

[[[ 1  5]
  [ 8 19]]

 [[35 52]
  [80 90]]]


In [11]:
a = np.array([[9,0],[9,0]])
print(a)

[[9 0]
 [9 0]]


In [12]:
a = np.array([[[30,40],[90,40]],[[30,30],[60,60]]])
print(a)
a.ndim

[[[30 40]
  [90 40]]

 [[30 30]
  [60 60]]]


3

In [13]:
#creating random arrays
np.random.randint([[[10,20],[2,6]],[[30,40],[20,10]]])

array([[[ 9,  7],
        [ 1,  0]],

       [[15, 29],
        [ 9,  3]]])

In [14]:
#creating random arrays
np.random.random((6,8))

array([[0.60019585, 0.49260811, 0.170395  , 0.7050418 , 0.7499478 ,
        0.63496769, 0.5898569 , 0.74317778],
       [0.59572185, 0.91507862, 0.73217186, 0.48588146, 0.4645006 ,
        0.67031248, 0.80014993, 0.83318436],
       [0.170949  , 0.59472074, 0.7812895 , 0.1294726 , 0.62582207,
        0.66765447, 0.64874647, 0.39968645],
       [0.30529784, 0.99459988, 0.45555227, 0.36190686, 0.27384704,
        0.58369505, 0.14744099, 0.58351911],
       [0.52682738, 0.95129012, 0.02637718, 0.28206216, 0.82435639,
        0.18093088, 0.3641265 , 0.8717726 ],
       [0.87593792, 0.88387595, 0.94869904, 0.03355449, 0.07068128,
        0.07995161, 0.10465548, 0.11711592]])

In [15]:
a=np.full((2),5)
print(a)

[5 5]


In [16]:
a = np.full((10,20),5)
print(a)

[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


In [17]:
a=np.full((2,3,4),6)
print(a)

[[[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]

 [[6 6 6 6]
  [6 6 6 6]
  [6 6 6 6]]]


In [19]:
#shape of an array
a = np.array([
    [[3,4],[50,4]],
    [[30,3],[75,6]]
    ])
print(a)
print(a.shape)

[[[ 3  4]
  [50  4]]

 [[30  3]
  [75  6]]]
(2, 2, 2)


In [20]:
#size of an array
a = np.array([
    [[3,4],[50,4]],
    [[30,3],[75,6]]
    ])
print(a)
print(a.size)

[[[ 3  4]
  [50  4]]

 [[30  3]
  [75  6]]]
8


In [21]:
#len of an array
a = np.array([
    [[3,4],[50,4]],
    [[30,3],[75,6]]
    ])
print(a)
len(a)

[[[ 3  4]
  [50  4]]

 [[30  3]
  [75  6]]]


2